version: "3"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        ports:
            - "${APP_PORT:-8000}:9000"
            # - "8000:9000"
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html

        volumes:
            - ./:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        depends_on:
            - db

    #MySQL Service
    db:
        image: mysql:8.0.26
        container_name: db
        platform: linux/amd64
        restart: unless-stopped
        # tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

#Docker Networks
networks:
    laravel:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
